import Head from 'next/head'

const about = () => {
    return (
        <>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <h1>About Page!</h1>
            </div>
        </>
    )
}

export default about