import Head from 'next/head'
import ArticleList from '../components/ArticleList'

export default function Home({ articles }) {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='keywords' content='web development, programming' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page!</h1>
        <ArticleList articles={articles} />
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=6`)
  const articles = await res.json()

  return {
    props: {
      articles
    }
  }

}