import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='keywords' content='web development, programming' />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Home Page!</h1>
      </main>
    </div>
  )
}